allowBuilds:
  '@parcel/watcher': true
  electron-winstaller: true
  esbuild: true

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - electron-winstaller

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - electron
  - esbuild
  - ffmpeg-static
