export const rawSoundData: [string, string][] = [
  ['sound/laugh-1.opus', 'Cười'],
  ['sound/laugh-2.opus', 'Cười 2'],
  ['sound/laugh-group.opus', 'Cười 3'],
  ['sound/cuoi-faptv.opus', 'Cười FTV'],
  ['sound/laughdiem.opus', 'Cười Điểm'],
  ['sound/cuoi-ba-dao.opus', 'Cười Đều'],
  ['sound/laughingdog.opus', 'Cười Chó'],
  ['sound/hyohyohyo.opus', 'Cười Hyo'],
  ['sound/haha-2.opus', 'Cười Trời Ơi'],
  ['sound/laughingkid.opus', 'Cười Trẻ Con'],
  ['sound/chinese-laugh.opus', 'Cười Trung'],
  ['sound/chienthang.opus', 'Cười Hẹ Hẹ'],
  ['sound/laugh-la.opus', 'Cười Lạ'],
  ['sound/ohnono.opus', 'Cười Oh No'],
  ['sound/laugh-male.opus', 'Cười Đàn Ông'],
  ['sound/laugh-child.opus', 'Cười Con Nít'],
  ['sound/laughhahe.opus', 'Cười Hả Hê'],
  ['sound/burstlaugh.opus', 'Cười Burst'],
  ['sound/ha-ha-ha.opus', 'Cười Bé'],
  ['sound/haha-3.opus', 'Cười Bé 2'],
  ['sound/hahahaha.opus', 'Cười Bé 3'],
  ['sound/cuoiembe.opus', 'Cười Bé 4'],
  ['sound/laughia.opus', 'Cười Ỉa'],
  ['sound/votay.opus', 'Vỗ Tay'],
  ['sound/votay-2.opus', 'Vỗ Tay 1'],
  ['sound/applause-cheer.opus', 'Vỗ Tay 2'],
  ['sound/applause-whistle.opus', 'Vỗ Tay 3'],
  ['sound/vo-tay-3.opus', 'Vỗ Tay 4'],
  ['sound/votaynao.opus', 'Vỗ Tay VD'],
  ['sound/kiss.opus', 'Nụ Hôn'],
  ['sound/kiss-2.opus', 'Nụ Hôn 2'],
  ['sound/kisslady.opus', 'Nụ Hôn Dài'],
  ['sound/kiss-male.opus', 'Nụ Hôn Trai'],
  ['sound/10diem.opus', '10 Điểm'],
  ['sound/khoai-khoai.opus', 'Khoái'],
  ['sound/oizoioi.opus', 'Ối Zời Ơi'],
  ['sound/aothatday.opus', 'Ảo Thật'],
  ['sound/quakeu.opus', 'Quạ Kêu'],
  ['sound/what.opus', 'What'],
  ['sound/nani.opus', 'Nani'],
  ['sound/shocked.opus', 'Shocked'],
  ['sound/bruh.opus', 'Bruh'],
  ['sound/wow.opus', 'Wow'],
  ['sound/wowamazing.opus', 'Amazing'],
  ['sound/nin.opus', 'Nín'],
  ['sound/quack.opus', 'Quack'],
  ['sound/tiengsung.opus', 'Súng'],
  ['sound/tat.opus', 'Tát'],
  ['sound/dam.opus', 'Đấm'],
  ['sound/punch2.opus', 'Đấm 2'],
  ['sound/punch3.opus', 'Đấm 3'],
  ['sound/punch4.opus', 'Đấm 4'],
  ['sound/lop1lop5.opus', 'Lớp 1/5'],
  ['sound/danhlonko.opus', 'Đánh Lộn'],
  ['sound/quatbatieu.opus', 'Quat Ba Tiêu'],
  ['sound/aidanhtaodi.opus', 'Đánh T Đê'],
  ['sound/tron-lam-sao.opus', 'Trốn Sao'],
  ['sound/nhieumau.opus', 'Máu'],
  ['sound/bay-oi.opus', 'Bây Ơi'],
  ['sound/roi-may-xong-roi.opus', 'Rồi M Xong'],
  ['sound/oi-ban-oi.opus', 'Ôi Bạn Ơi'],
  ['sound/da-lam-gi-dau.opus', 'Đã Làm J Đâu'],
  ['sound/so-qua.opus', 'Sợ Quá'],
  ['sound/fart.opus', 'Fart'],
  //  ["sound/fart-wet.opus", "Fart Wet"],
  ['sound/snore-mimi.opus', 'Ngáy Mimi'],
  ['sound/luon-leo.opus', 'Lươn Lẹo'],
  ['sound/chayeuem.opus', 'Chả Yêu Em'],
  ['sound/ghe-chua.opus', 'Ghê Chưa'],
  ['sound/khochuhu.opus', 'Khóc'],
  ['sound/khocnhe.opus', 'Khóc Nhè'],
  ['sound/helpme.opus', 'Help Me'],
  ['sound/cuutui.opus', 'Cứu Tui'],
  ['sound/gi-z-troi.opus', 'J Trời'],
  ['sound/cai-gi-do-ba-noi.opus', 'J Bà Nội'],
  ['sound/ua-j-zo.opus', 'Ủa J Zợ'],
  ['sound/uitroidat.opus', 'Ui Trời Đất'],
  ['sound/day-toi-biet-ngay.opus', 'T Biết Ngay'],
  //  ["sound/gameover.opus", "Game Over"],
  ['sound/daygaydi.opus', 'Dậy Gáy Đi'],
  ['sound/noi-the-thi-chiu.opus', 'Nói Thế Chịu'],
  ['sound/hong-biet-nua.opus', 'Hong Biết Nữa'],
  ['sound/oiconsong.opus', 'Con Sông Quê'],
  ['sound/chi-lay-em.opus', 'Chị Lạy Em'],
  ['sound/concainit.opus', 'Còn Cái Nịt'],
  ['sound/bietgichua.opus', 'Hết Tiền'],
  ['sound/troidatdth.opus', 'Trời Đất Dth'],
  ['sound/colen.opus', 'Cố Lên'],
  ['sound/gaithich.opus', 'Chiêu Con Gái'],
  ['sound/giangho.opus', 'Giang Hồ'],
  ['sound/thatim.opus', 'Thả Tim'],
]
